spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/schooldb
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
